name: main

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release_please
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: node

      - run: ./script/build
        shell: bash

  deploy:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - run: ./script/deploy "${{ steps.release_please.outputs.version }}" "${{ steps.release.outputs.tag_name }}"
        if: ${{ steps.release_please.outputs.release_created }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
